/**
 * Downloads Mega Millions and Powerball drawing history from the New York
 * State open-data portal (Socrata) and writes data/draws.json plus
 * data/draws.js (a plain script, so the app also runs straight from file://).
 *
 * Only drawings from each game's current ball matrix are kept:
 *   Mega Millions  5/70 + 1/25  from 2017-10-31 (mega ball became 1-24 in 2025)
 *   Powerball      5/69 + 1/26  from 2015-10-07
 *
 * Run: node tools/fetch-draws.mjs
 */

import { writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_JSON = resolve(HERE, "..", "data", "draws.json");
const OUT_JS = resolve(HERE, "..", "data", "draws.js");

const SOURCES = {
  megamillions: {
    label: "Mega Millions",
    dataset: "5xaw-6ayf",
    title: "Lottery Mega Millions Winning Numbers: Beginning 2002",
    select: "draw_date,winning_numbers,mega_ball",
    specialField: "mega_ball",
    from: "2017-10-31",
  },
  powerball: {
    label: "Powerball",
    dataset: "d6yy-54nr",
    title: "Lottery Powerball Winning Numbers: Beginning 2010",
    select: "draw_date,winning_numbers",
    specialField: null,
    from: "2015-10-07",
  },
};

function parseRow(row, source) {
  const numbers = String(row.winning_numbers ?? "")
    .trim()
    .split(/\s+/)
    .map(Number)
    .filter((n) => Number.isInteger(n) && n > 0);

  let main = numbers;
  let special = source.specialField ? Number(row[source.specialField]) : NaN;

  // Older rows pack the special ball into winning_numbers as the sixth value.
  if (main.length === 6 && !Number.isInteger(special)) {
    special = main[5];
    main = main.slice(0, 5);
  } else if (main.length === 6) {
    main = main.slice(0, 5);
  }

  if (main.length !== 5 || !Number.isInteger(special)) return null;
  return { d: String(row.draw_date).slice(0, 10), n: main.slice().sort((a, b) => a - b), s: special };
}

async function fetchGame(key, source) {
  const url =
    `https://data.ny.gov/resource/${source.dataset}.json` +
    `?$select=${encodeURIComponent(source.select)}` +
    `&$where=${encodeURIComponent(`draw_date >= '${source.from}'`)}` +
    `&$order=${encodeURIComponent("draw_date DESC")}&$limit=50000`;

  const res = await fetch(url, { headers: { accept: "application/json" } });
  if (!res.ok) throw new Error(`${key}: source responded ${res.status} ${res.statusText}`);

  const rows = await res.json();
  const draws = rows
    .map((row) => parseRow(row, source))
    .filter(Boolean)
    .filter((draw) => draw.d >= source.from)
    .sort((a, b) => (a.d < b.d ? 1 : a.d > b.d ? -1 : 0));

  if (draws.length < 100) throw new Error(`${key}: suspiciously few draws parsed (${draws.length})`);

  return {
    source: `data.ny.gov · ${source.title} (${source.dataset})`,
    count: draws.length,
    latestDraw: draws[0].d,
    firstDraw: draws[draws.length - 1].d,
    draws,
  };
}

const games = {};
for (const [key, source] of Object.entries(SOURCES)) {
  games[key] = await fetchGame(key, source);
  const g = games[key];
  console.log(
    `${source.label.padEnd(14)} ${g.count} draws  ${g.firstDraw} .. ${g.latestDraw}` +
      `  main max ${Math.max(...g.draws.flatMap((d) => d.n))}` +
      `  special ${Math.min(...g.draws.map((d) => d.s))}-${Math.max(...g.draws.map((d) => d.s))}`,
  );
}

const snapshot = { fetchedAt: new Date().toISOString(), games };

await mkdir(dirname(OUT_JSON), { recursive: true });
await writeFile(OUT_JSON, JSON.stringify(snapshot), "utf8");
await writeFile(
  OUT_JS,
  `/* Auto-generated by tools/fetch-draws.mjs - do not edit by hand. */\n` +
    `window.LOTTO_SNAPSHOT = ${JSON.stringify(snapshot)};\n`,
  "utf8",
);

console.log(`\nwrote ${OUT_JSON}`);
console.log(`wrote ${OUT_JS}`);
